const express = require('express');
const cors = require('cors');
const fs = require('fs');
const https = require('https');

// passport and jwt authentication
const passport = require('passport');
const BasicStrategy = require('passport-http').BasicStrategy;
const JwtStrategy = require('passport-jwt').Strategy;
const ExtractJwt = require('passport-jwt').ExtractJwt;
const jwt = require('jsonwebtoken');

// const SECRET_KEY = 'SECRET_KEY';

const repository = require('./repository/');

const postsRouter = require('./controllers/postsRouter');
const commentsRouter = require('./controllers/commentsRouter');
const offensiveRouter = require('./controllers/offensiveRouter');
const authRouter = require('./controllers/authRouter');


const app = express();
// Enable CORS
app.use(cors());
// Convert json bodies to JavaScript object
app.use(express.json());

// passport authentication
app.use(passport.initialize());

// routes
app.use('/login', authRouter);
app.use('/posts', postsRouter);
app.use('/posts/:id/comments', commentsRouter);
app.use('/offensive-words', passport.authenticate('jwt', { session: false }), offensiveRouter);


async function main() {
  await repository.connect();
  
  await repository.checkDefault();
}

main();

// to create a new autogenerated false safe certificate
// openssl req -nodes -new -x509 -keyout server.key -out server.cert
https.createServer({
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.cert'),
}, app).listen(3443, () => {
  console.log('Https server started in port 3443');
});